import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ReactQueryProvider from './components/react-query-provider';
import Navbar from './components/navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <header className="bg-blue-500 text-white p-4 shadow-md">
            <h1 className="text-2xl font-bold">Monetary Penalty System</h1>
          </header>
          <Navbar />
          <main className="container mx-auto p-4">{children}</main>
          <footer className="bg-gray-800 text-white p-4 mt-8 text-center">
            <p>&copy; 2025 Monetary Penalty System. All rights reserved.</p>
          </footer>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
